services:
  - type: web
    name: ship-optimizer-app
    env: python
    runtime: python3.11 # Matches runtime.txt
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME # Replace with your GitHub repo URL
    branch: main # Or your default branch
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn --chdir src main:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9 # Matches runtime.txt
      - key: WEB_CONCURRENCY # Optional: Adjust based on Render plan
        value: 4
